### ISSUE TITLE
Inner borders

### ISSUE THREAD

**Issue by thomasobrien99** [kirankalyan5/react-native-segmented-control-tab#11]
Hello @kirankalyan5, thanks for the nice component! I am wondering if you would be open to a PR for setting right and left borders a bit differently, because as it is now inner cells left and right borders join and double up. If You would like to keep the default as is, I could also make it based on an optional prop. I would simply omit the the left border on all except the first tab. Thanks in advance for your reply!

**Comment by kirankalyan5** [comment]
Hi @thomasobrien99, you can do the changes and open a PR. Let me have a look on it :)

Plus:I can suggest you a simple hack, may be you can give a try.  you can also play around with the existing one by giving inner border value to "Half of it's value" so when it doubles it would render as expected :) 

Thanks in advance for your contribution 👍

**Comment by kirankalyan5** [comment]
@thomasobrien99 I have published the latest one.

**Comment by thomasobrien99** [comment]
@kirankalyan5 Thank you so much! unfortunately the way the styles are were not working well for us across both android and ios, I believe due to a react native bug with regard to border radius (particularly when the border is very small), so I had to re-implement it in a different way. Thank you for following up with this!
