### ISSUE TITLE
release to npm with first and last tab style overloading please

### ISSUE THREAD

**Issue by mathieujohnson** [kirankalyan5/react-native-segmented-control-tab#111]
Hello, I see the code is in master and would like to use this feature. Is it possible to release it to NPM?

**Comment by kirankalyan5** [comment]
Hi @mathieujohnson, apologies for the delay, I will soon publish the latest version and keep you posted.
Thanks

**Comment by kirankalyan5** [comment]
@mathieujohnson v3.4.1 is published 👍
