### ISSUE TITLE
introduce Tab bar images

### ISSUE THREAD

**Issue by kirankalyan5** [kirankalyan5/react-native-segmented-control-tab#113]
Introduce and make the component configurable to display images(optional) along with the text value when needed.

**Comment by ziyafenn** [comment]
Just to add, I believe it would make sense to allow various types of objects and not only images. I.e. an icon component (RN vector icons).

**Comment by kirankalyan5** [comment]
@ziyafenn Makes sense 👍

**Comment by 0x0056** [comment]
I have made a PR for this @ #115
