### ISSUE TITLE
Ability to change touchable

### ISSUE THREAD

**Issue by iRoachie** [kirankalyan5/react-native-segmented-control-tab#114]
Would be awesome if we could change the type of Touchable being used.

Right now it’s `TouchableOpacity`. Would be awesome if we could use `TouchableHighlight`

**Comment by kirankalyan5** [comment]
Hi, @iRoachie Would be great if could briefly explain the use case?
Thanks

**Comment by iRoachie** [comment]
The original segmental control on iOS used TouchableHighlight. When tapping on an item, it shows an underColor. Right now you lib doesn’t have any effects at all when touching on an item since you’re using TouchableOpacity with `activeOpacity` of 1. 

Changing this `activeOpacity` dims the opacity of the entire item including the borders.

**Comment by kirankalyan5** [comment]
ok, then the better idea would be to configure the component to use one of the `Touchable...` via props with a default one.

I'm bit occupied at the moments, I could look into it sometime later or PR's welcome :)
