### ISSUE TITLE
How can I pass 2nd index to onTabPress callback?

### ISSUE THREAD

**Issue by emclab** [kirankalyan5/react-native-segmented-control-tab#133]
In my app, I need to pass 2nd index into onTabPress callback. How can I do it? Here is the code:

                             <SegmentedControlTab
                                    values={['messanger', 'eventer', 'admin']}
                                    selectedIndex={this.state.selectedIndex}
                                    onTabPress={this.handleIndexChange}
                                    tabsContainerStyle={styles.tabContainerStyle}
                                />

The method handleIndexChange only takes in only one index:

                       handleIndexChange = index => {...}

I would like to have something like below:

         handleIndexChange = (index, 2ndIndex) => { .... }

Many thanks!

**Comment by kirankalyan5** [comment]
Hi @emclab  Could you explain in a bit detail the purpose of the second index like how you get it and why you need it?

**Comment by emclab** [comment]
Hi @kirankalyan5, the purpose of adding a 2ndindex is to provide a identifier when the segement tab is grouping within a something else, such as checkbox. It would be nice to have. I am currently solving the issue by creating a component for that grouping so I can pass in a 2nd index as variable outside of the segment tab control.
