### ISSUE TITLE
iOS 13 has a new style of segment

### ISSUE THREAD

**Issue by shamilovtim** [kirankalyan5/react-native-segmented-control-tab#145]
Consider providing an option to use the new style in order to stay consistent with at least one platform

![segmented](https://user-images.githubusercontent.com/3495974/66773183-7d81c700-ee8c-11e9-8306-c1d0c9426cad.png)

**Comment by vforvasile** [comment]
Try this workaround:
`const styles = {
  container: {
    height: 36,
    borderColor: '#eeeef0',
    backgroundColor: '#eeeef0',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    borderRadius: 8,
    overflow: 'hidden'
  },
  commonStyle: {
    backgroundColor: '#eeeef0',
    height: 30,
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    padding: 2,
    margin: 5,
    border: 'transparent',
    borderWidth: 0
  },
  activeStyle: {
    backgroundColor: '#fff',
    shadowOffset: { width: 0.95, height: 0.95 },
    shadowColor: '#a2a2a2',
    shadowOpacity: 0.5,
    shadowRadius: 2
  },
  text: {
    color: '#444444',
    fontWeight: 'bold'
  }
};

export const SegmentedTabs = ({ handleTabPress, selectedIndex, values }) => (
  <SegmentedControlTab
    values={values}
    selectedIndex={selectedIndex}
    onTabPress={handleTabPress}
    borderRadius={8}
    tabsContainerStyle={styles.container}
    tabStyle={styles.commonStyle}
    activeTabStyle={{ ...styles.commonStyle, ...styles.activeStyle }}
    tabTextStyle={styles.text}
    activeTabTextStyle={styles.text}
  />
);
`

**Comment by shamilovtim** [comment]
Nice job! If you're interested, you could probably send a PR to the repo and have this style be conditional on a true/false prop `newSegmentStyle`. One thing, you might be missing the animation left to right. I'll be happy to add that when I get a second.

**Comment by alyezz** [comment]
@shamilovtim I was wondering if you ever got the chance to implement the animation? Or have any insight as to how to do it

**Comment by shamilovtim** [comment]
@alyezz Sorry but I've been too busy and haven't needed to yet! I do have insight on how to use it: use the native React Native.Animation API. I'd wait for the javascript computation to complete and then rerender the view in that order.

**Comment by Norcy** [comment]
any update here?
