### ISSUE TITLE
When this component is loading in a scrollview as initial loading, this one isn't shown on scrollview.

### ISSUE THREAD

**Issue by ghost** [kirankalyan5/react-native-segmented-control-tab#15]
How are you?
I put this component in my project, and put this one in any scrollview.
When i run my app initially, this component isn't shown on my app.
![simulator screen shot 6 apr 2017 3 34 46 pm](https://cloud.githubusercontent.com/assets/23254736/24742883/b489f95e-1ade-11e7-9666-b79f766b36b4.png)

But when i change the state of scrollview by scrolling, your component is shown.
![simulator screen shot 6 apr 2017 3 34 22 pm](https://cloud.githubusercontent.com/assets/23254736/24742894/bcf5d86a-1ade-11e7-8710-511b244b1eea.png)

So that is my fault?
Would you please help me ASAP?

**Comment by kirankalyan5** [comment]
@WernlingTan can you please share the code as well ?

**Comment by WernlingTan** [comment]
Thanks

Followings is the render function on my code.


  render() {

    return (
      <View style={Styles.listContainer}>
        <View style={[Styles.listContainer, { flex: 1, }]}>
          <ScrollView style={{ flex: 1, padding: 20 }}>
          ... ... ...
            <SegmentedControlTab
                values={["1+",
                        "2+",
                        "3+",
                        "4+",
                        "5+",
                        "6+", ]}
                selectedIndex = {this.state.selectedItemOfBaths}
                onTabPress={this.onTabPressBaths.bind(this)} />            
          ... ... ...
          </ScrollView>
        </View>
      </View>
    );
  }

**Comment by alexdunae** [comment]
I'm seeing this as well when I nest a SegmentedControlTab in a ScrollView (specifically https://github.com/APSL/react-native-keyboard-aware-scroll-view which wraps a regular RN ScrollView).

**Comment by kirankalyan5** [comment]
@alexdunae did it fix the issue by adding removeClippedSubviews={false} ?

**Comment by alexdunae** [comment]
It did - I just created a pull request.  Tested on iOS but not Android.
