### ISSUE TITLE
set selected index by this.setState() doesn't work!

### ISSUE THREAD

**Issue by Kerence** [kirankalyan5/react-native-segmented-control-tab#17]
I've found a way to fix this issue!
add the following code to SegmentedControlTab to get this issue fixed.
...
 componentWillReceiveProps(props){
        const {selectedIndex} = props;
        if(selectedIndex){
            this.setState({selectedIndex});
        }
    }
....

**Comment by sternjobname** [comment]
Could you show this in context with the rest of your code?  It's unclear as to how this is implemented...

**Comment by kirankalyan5** [comment]
@Kerence can to detail a bit more on this issue.

**Comment by kirankalyan5** [comment]
Not reproducible, Closing this issue.
