### ISSUE TITLE
Follow semantic versioning

### ISSUE THREAD

**Issue by jevakallio** [kirankalyan5/react-native-segmented-control-tab#2]
The repository readme says
> Lasted code in the repo let to be published with more flexibility in styling.(v1.0.4)- coming soon 

According to https://github.com/kirankalyan5/react-native-segmented-control-tab/commit/0d7827263fe17fd2559d6485899a32221724c6e3 the next version will introduce breaking changes. According to the [semver](http://semver.org/) guidelines, breaking changes should cause a major version bump:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes

The next release should therefore be 2.0.0. The release will otherwise break any consumers' builds, unless they have pinned a specific patch version.

Thanks!

**Comment by kirankalyan5** [comment]
jevakallio, Thanks for this, will be following this approach.
