### ISSUE TITLE
Gradient BackgroundColor

### ISSUE THREAD

**Issue by ssghajar** [kirankalyan5/react-native-segmented-control-tab#202]
hi there ...thanks for the repo.
is it possible to set a gradient color style for each segment?
or use `react-native-linear-gradient` in it?

**Comment by kirankalyan5** [comment]
@ssghajar Thank you.

you could play around with the following tab style props to achieve a custom tab styling.
```
firstTabStyle,
lastTabStyle,
tabStyle,
activeTabStyle,
tabTextStyle,
```
