### ISSUE TITLE
Why not use Native Segmented control on iOS and the custom one on Android?

### ISSUE THREAD

**Issue by elie222** [kirankalyan5/react-native-segmented-control-tab#21]
Why not use Native Segmented control on iOS and the custom one on Android since it would have better performance?

**Comment by kirankalyan5** [comment]
@elie222 the main concept here was to write minimal and common code for both IOS and Android.

**Comment by elie222** [comment]
I've just tried it for the first time. The gif you show doesn't show the whole picture. You lose animations when you don't use the default iOS segmented control.
