### ISSUE TITLE
feature request: enabled property

### ISSUE THREAD

**Issue by jamesholcomb** [kirankalyan5/react-native-segmented-control-tab#22]
Per https://facebook.github.io/react-native/docs/segmentedcontrolios.html#enabled

**Comment by kirankalyan5** [comment]
Nice to have! PR welcome.

**Comment by jamesholcomb** [comment]
Gist for anyone wanting to create a PR: https://gist.github.com/jamesholcomb/ab6e3a58cccbe5ead7af1c60f14bc76f

// Added disabled prop
// Use Material theme Indigo color defaults
// Add propType validation
// Lower opacity for disabled
// Fix border and width issues for Android

**Comment by kirankalyan5** [comment]
@jamesholcomb thanks, this issue will be tracked as part of #33
