### ISSUE TITLE
Segments change size on first press

### ISSUE THREAD

**Issue by Un3qual** [kirankalyan5/react-native-segmented-control-tab#23]
![jun-07-2017 20-03-02](https://user-images.githubusercontent.com/6117075/26910558-8301f6fc-4bbc-11e7-9786-a0d97dd784ee.gif)
The above happens, but as soon as the segments resize, the resizing stops. I switched to [ArnaudRinquin/react-native-radio-buttons](https://github.com/ArnaudRinquin/react-native-radio-buttons) due to this, but it happened with that repo too. I'm not even sure where to mention this because it happens on both.

**Comment by kirankalyan5** [comment]
@Un3qual I doubt the custom styles of yours is causing this issue. on observation it's resetting the padding. Can you share the code how you have consumed.

**Comment by Un3qual** [comment]
```jsx
<SegmentedControls
              tint={Colors.primary.base}
              selectedTint={Colors.white}
              backTint={Colors.white}
              optionStyle={styles.optionStyle}
              containerStyle={styles.optionsContainerStyle}
              width={1}
              options={props.sortOptions}
              onSelection={props.onSortSelection}
              selectedOption={props.selectedSort}
              testOptionEqual={(a, b) => {
                if (!a || !b) {
                  return false
                }
                return a === b
              }}
            />
```
```es6
optionStyle: {
    flex: 1,
    fontFamily: Fonts.Font.base,
    paddingTop: 0,
  },
  optionsContainerStyle: {
    flex: 1,
    marginLeft: 10,
    marginRight: 10,
  },
```

**Comment by kirankalyan5** [comment]
@Un3qual is it[ kirankalyan5/react-native-segmented-control-tab](https://github.com/kirankalyan5/react-native-segmented-control-tab) at first place ?

**Comment by Un3qual** [comment]
Whoops. I sent the wrong code. here is the right one:
```jsx
<SegmentedControlTab
  values={props.sortOptions}
  selectedIndex={props.selectedSort}
  onTabPress={props.onSortSelection}
/>
```

**Comment by kirankalyan5** [comment]
@Un3qual I tested this again, works fine for me. Can you test it again.

**Comment by kirankalyan5** [comment]
@Un3qual I'm closing this issue as I see it works as expected.

Thanks
