### ISSUE TITLE
Truncate text inside tab with ellipsis

### ISSUE THREAD

**Issue by emroussel** [kirankalyan5/react-native-segmented-control-tab#25]
There are some cases where the text I display inside the segmented control does not fit on one line. It would be nice to be able to truncate the text like on `TextInput` with `numberOfLines`.

React Native's `SegmentedControlIOS` already does this by default.

I can submit a PR with the fix if you want!

**Comment by kirankalyan5** [comment]
Hi @emroussel thanks for the suggestion, I have added the code for this. It will be up in the next version.which I will be publishing today.

![image](https://user-images.githubusercontent.com/13114538/27813269-5be0f9c0-6092-11e7-8a51-429184a585f4.png)

**Comment by karan101292** [comment]
Not a good idea to make it like this. make it configurable to set number of lines. Right now I am using it by changing it in source code.

**Comment by kirankalyan5** [comment]
@karan101292 Yes, we should make it configurable! @bgold0  `<SegmentedControlTab numberOfLines={2}` will not work as it not a valid prop for `SegmentedControlTab`.if 

@karan101292 if you have the changes ready, please raise PR.

**Comment by josoma03** [comment]
Change the size of segment
`tabStyle={{ flex: 0, flexGrow: 1}}`
