### ISSUE TITLE
Change View.propTypes to ViewPropTypes to support React Native v44 

### ISSUE THREAD

**Issue by RP20** [kirankalyan5/react-native-segmented-control-tab#28]
in SegmentedControl.js

SegmentedControlTab.propTypes = {
    values: PropTypes.array,
    badges: PropTypes.array,
    multiple: PropTypes.bool,
    onTabPress: PropTypes.func,
    selectedIndex: PropTypes.number,
    selectedIndices: PropTypes.arrayOf(PropTypes.number),
    tabsContainerStyle: View.propTypes.style,
    tabStyle: View.propTypes.style,
    activeTabStyle: View.propTypes.style,
    tabTextStyle: Text.propTypes.style,
    activeTabTextStyle: Text.propTypes.style,
    tabBadgeContainerStyle: Text.propTypes.style,
    activeTabBadgeContainerStyle: Text.propTypes.style,
    tabBadgeStyle: Text.propTypes.style,
    activeTabBadgeStyle: Text.propTypes.style,
    borderRadius: PropTypes.number
}

**Comment by kirankalyan5** [comment]
@RP20 it has been updated way back to ViewPropTypes, I doubt you are referring to fork.

Please have a look here - [SegmentedControlTab.js](https://github.com/kirankalyan5/react-native-segmented-control-tab/blob/master/SegmentedControlTab.js)

**Comment by RP20** [comment]
@kirankalyan5 , Thanks.
