### ISSUE TITLE
  android中 三个选项卡的时候 点击第三个选项右边有一半无法触发点击事件

### ISSUE THREAD

**Issue by hxx1197411446** [kirankalyan5/react-native-segmented-control-tab#29]
<SegmentedControlTab
                        values={['买入', '卖出','撤单']}
                        selectedIndex={this.state.customStyleIndex}
                        onTabPress={this.handleSelect}
                        borderRadius={0}
                        tabsContainerStyle={{ height: p(60), backgroundColor: '#1F2229',marginVertical:p(20)}}
                        tabStyle={{ backgroundColor: '#1F2229', borderWidth: StyleSheet.hairlineWidth, borderColor:'#313840'}}
                        activeTabStyle={{ backgroundColor: '#313840'}}
                        tabTextStyle={{ color: '#FFFFFF', fontWeight: 'bold' }}
                        activeTabTextStyle={{ color: '#FFFFFF' }} />

handleSelect = (index) => {
        console.log('index',index);
        this.setState({
            ...this.state,
            customStyleIndex: index,
        });
    };

**Comment by kirankalyan5** [comment]
@hxx1197411446  非常感谢你 

P.S used google translator :D
