### ISSUE TITLE
Vertical Design of segment

### ISSUE THREAD

**Issue by prushni1** [kirankalyan5/react-native-segmented-control-tab#302]
Can we place the labels in vertical format, rather than horizontal view?

**Comment by kirankalyan5** [comment]
Hi @prushni1 The default flexDirection for `tabsContainerStyle` is `row`
 https://github.com/kirankalyan5/react-native-segmented-control-tab/blob/master/src/SegmentedControlTab.js#L46

You could override it with the prop `tabsContainerStyle`and passing`flexDirection: 'column',`.
