### ISSUE TITLE
Add support for disabled tab

### ISSUE THREAD

**Issue by ziyafenn** [kirankalyan5/react-native-segmented-control-tab#33]
Hi guys. I think that would be great to be able to disable certain tabs and style them. 

Thanks! 💯

**Comment by kirankalyan5** [comment]
Hi @ziyafenn, Thanks for the thought, I'm currently little occupied. PR welcome.

**Comment by ziyafenn** [comment]
Tried to do it, but unfortunately, this is beyond my knowledge :(. Would appreciate someone taking look into it.

**Comment by kirankalyan5** [comment]
Np, but I'm not really sure will it be a good idea to make it able to disable.  Could you please share some use cases in how useful it will be terms of segmented control tab?

**Comment by ziyafenn** [comment]
@kirankalyan5 of course i can.

We have a game companion app which supports 3 different game platforms (ps4, xbox, pc). And when a user registers he can select his platform. For the beginning, we offer only ps4, but we still want to people know that we have other platforms coming too. This is why we want to disable the other two.

Hope this clarifies for you the use case.

**Comment by kirankalyan5** [comment]
Thanks! I will soon add a prop `enable` which would match native implementation -https://facebook.github.io/react-native/docs/segmentedcontrolios#enabled.

Not sure whether that will help you,

**Comment by kirankalyan5** [comment]
@ziyafenn As discussed earlier, I have added the `enabled` prop. you can also slightly customize the disabled view with `tabsContainerDisableStyle`.

Please check the latest version.

**Comment by waltermvp** [comment]
@ziyafenn any plans for enabled a single tab?

**Comment by waltermvp** [comment]
If original component does not support then i would agree with you.

**Comment by ziyafenn** [comment]
hey @kirankalyan5 ! sorry for silly question, but does enable prop works for the whole tab component and not for the tab item, right? Cause i needed to disable a tab items :D 

Thanks

**Comment by kirankalyan5** [comment]
it just works similar to the RN's SegmentmentedControlIOS,

[SegmentmentedControlIOS](https://facebook.github.io/react-native/docs/segmentedcontrolios#enabled)

https://facebook.github.io/react-native/docs/segmentedcontrolios#enabled
