### ISSUE TITLE
how do i remove the color blueish border color on the selected Tab ?

### ISSUE THREAD

**Issue by jpca999** [kirankalyan5/react-native-segmented-control-tab#34]
![image](https://user-images.githubusercontent.com/1026325/32743443-664e8882-c87a-11e7-9325-a275642ace08.png)

        <SegmentedControlTab
            tabsContainerStyle={styles.tabsContainerStyle}
            tabStyle={styles.tabStyle}
            tabTextStyle={styles.tabTextStyle}
            activeTabStyle={styles.activeTabStyle}
            activeTabTextStyle={styles.activeTabTextStyle}

      tabsContainerStyle: {
          //custom styles
        },
        tabStyle: {
          //custom styles
          },
        tabTextStyle: {
          //custom styles
        },
        activeTabStyle: {
          //custom styles
          backgroundColor: '#D52C43'
          },
        activeTabTextStyle: {
          //custom styles
          backgroundColor: '#D52C43'
        },
        tabBadgeContainerStyle: {
          //custom styles
          backgroundColor: '#D52C43',
          color: '#D52C43'
        },
        activeTabBadgeContainerStyle: {
          //custom styles
        },
        tabBadgeStyle: {
          //custom styles
        },
        activeTabBadgeStyle: {
          //custom styles
        }

  });

  //

  //

**Comment by kirankalyan5** [comment]
@jpca999 you can override by giving border color to tabStyle prop

```
tabStyle: {
        borderColor: '#D52C43'
    }
```
![image](https://user-images.githubusercontent.com/13114538/32698793-3f8b5224-c7d1-11e7-8b86-a822000ff1f2.png)

Also if you want the text color to be red then you can override by giving color to tabTextStyle
```
tabTextStyle: {
        color: '#D52C43'
    }
```
![image](https://user-images.githubusercontent.com/13114538/32698830-ba9cd51e-c7d1-11e7-9a05-bde6b388c03c.png)

Hope this helps!

**Comment by jpca999** [comment]
thanks @kirankalyan5
