### ISSUE TITLE
How to put a vertical line as separator ?

### ISSUE THREAD

**Issue by jgutierrez11** [kirankalyan5/react-native-segmented-control-tab#35]
How to style the control in order to achieve something like:

Option1    |       Option2

**Comment by kirankalyan5** [comment]
@jgutierrez11 could you share the actual design which you want to produce using this component.

**Comment by Hyeongwon** [comment]
easily

```
<View
  style={{
  borderLeftWidth: 1,
  borderLeftColor: 'white',
  }}
/>
```

**Comment by kirankalyan5** [comment]
closing this as it's inactive for a long time.

**Comment by kirankalyan5** [comment]
closing this as it's inactive for a long time.

**Comment by kirankalyan5** [comment]
closing this as it's inactive for a long time.
