### ISSUE TITLE
borderWidth not rendering at left and right side

### ISSUE THREAD

**Issue by my-name-is-nheo** [kirankalyan5/react-native-segmented-control-tab#351]
![image](https://user-images.githubusercontent.com/58013260/149409746-9847b7de-2844-4a7c-a271-fb87ac62ea61.png)

CODE: 
![image](https://user-images.githubusercontent.com/58013260/149409904-0a9f0d8f-cc47-4b0e-b23d-eee907b8f9d5.png)

tried
`borderWidth: 1` for activeTabStyle, tabStyle and firstTabStyle. none seem to work. I'm seeing `borderRightWidth` and `borderLeftWidth` is 0 in the inspector. Where can i update this?

**Comment by kirankalyan5** [comment]
Hi, Is this happening on all the tabs or just the active tab? 
And in general how many tabs are you rendering?

**Comment by my-name-is-nheo** [comment]
@kirankalyan5 happens when there is only tab. when there are three tabs, only the middle one will show all borders. first and last tab have the same behavior. First tab's `borderRightWidth` is set to 0 and last tab's `borderLeftWidth` is set to 0. cannot override them for some reason

**Comment by kirankalyan5** [comment]
Could you try passing custom styles to `firstTabStyle`, `lasttabStyle`?
That would override the default styles, also in the above code I see you are passing an array, please try passing object styles instead.
```javascript
<SegmentedControltab
  ...
  ...
  firstTabStyle={ borderRightWidth: 1 }
  lasttabStyle={ borderLeftWidth: 1 }
```
