### ISSUE TITLE
How to change the page when tab index changed

### ISSUE THREAD

**Issue by Jack-Wen** [kirankalyan5/react-native-segmented-control-tab#4]
How to change the page when tab index changed?

**Comment by kirankalyan5** [comment]
![image](https://cloud.githubusercontent.com/assets/13114538/20656202/372c55b8-b550-11e6-8290-e4906bc074a0.png)

you can use this call back, with the help of the local state and index you can render/ change the View.

**Comment by Jack-Wen** [comment]
thanks , I use onTabPress= { index => this.setState({selected:index})} , but I got the follow issue with es6.
![image](https://cloud.githubusercontent.com/assets/8498242/20699307/942d0b44-b641-11e6-9509-b168069df71e.png)

my constructor
![image](https://cloud.githubusercontent.com/assets/8498242/20699414/332a9cd4-b642-11e6-9964-26e22e479eef.png)

**Comment by kirankalyan5** [comment]
Hi Jack-Wen, I have updated the example for the usage of the index. please take the latest and refer [example.js](https://github.com/kirankalyan5/react-native-segmented-control-tab/blob/master/Example/example/exampleMain.js#L14).

**Comment by Jack-Wen** [comment]
thanks! it good running.
