### ISSUE TITLE
Segmented size according to children

### ISSUE THREAD

**Issue by WeiLiangTan** [kirankalyan5/react-native-segmented-control-tab#42]
Is there a way to have the controls's width scaling depending on the options?

Rather than setting the width, I hope it can change according to the text, and not necessary to fill the parent's width.

For example,
![screen shot 2018-03-22 at 4 22 15 pm](https://user-images.githubusercontent.com/8586548/37759040-5c6de8ca-2ded-11e8-961d-4dfa90063ce7.png)

**Comment by kirankalyan5** [comment]
@WeiLiangTan it always spaces evenly as they look neat and identical. I don't think it will be a good idea to set the width of the tab (of segmentedControl) according to the text.

**Comment by Sebi55** [comment]
You should be able to pass other tabStyle options to allow this. I am using these settings to size the tabs according to the text inside:

```
    flex: 0,
    flexGrow: 1,
```

**Comment by Jamaxack** [comment]
In case someone looking for making the SegmentedControlTab control alight center, here how I did:
`  <View style={{ alignItems: "center", paddingTop: 10 }}>
          <SegmentedControlTab
            tabStyle={{ flex: 0, paddingHorizontal: 20 }}
            values={["Upcoming", "Past"]}
          />
        </View>`
