### ISSUE TITLE
Can't get rid of ellipsis's

### ISSUE THREAD

**Issue by bgold0** [kirankalyan5/react-native-segmented-control-tab#44]
When I this:

`values={['something', 'something else', 'see this']`

I get ellipsis like so:

<img width="239" alt="screen shot 2018-04-06 at 4 22 20 pm" src="https://user-images.githubusercontent.com/4645400/38442602-ceeb90e4-39b6-11e8-92cc-0ffb31070116.png">

Anyway I can make it go to a new line?

**Comment by kirankalyan5** [comment]
Hi @bgold0 currently the tab options <Text> numberOfLines is set to 1 and the ellipsizeMode is ture.
We could make it configurable with props. PR welcome for this change :)

**Comment by kirankalyan5** [comment]
I will be making number if line configurable soon.
Thanks

**Comment by kresogalic8** [comment]
Hey guys, is this fixed? I have that issue also, how can I get 2 lines?

**Comment by kirankalyan5** [comment]
Please use `textNumberOfLines={2}` prop.

**Comment by kresogalic8** [comment]
@kirankalyan5 that's not working

**Comment by kirankalyan5** [comment]
Would be nice if you could share the code in how you are using it?

**Comment by kresogalic8** [comment]
This is what I have in code
`
SegmentedControlTab
    values={this.state.eventTypes}
    selectedIndex={this.state.selectedType}
    onTabPress={this.handleIndexChange}
    tabsContainerStyle={{ height: 40 }}
    activeTabStyle={{
        backgroundColor: COLORS.secondary
    }}
    activeTabTextStyle={{ color: 'white' }}
    tabStyle={{
        borderColor: COLORS.secondary
    }}
    tabTextStyle={{
        color: COLORS.dark,
        fontSize: 12
    }}
    textNumberOfLines={2}
/>
`

**Comment by kirankalyan5** [comment]
Could you please check if you have the latest version?

**Comment by kresogalic8** [comment]
<img width="834" alt="Screenshot 2019-09-16 at 22 36 52" src="https://user-images.githubusercontent.com/7289406/64991826-e77d6f80-d8d2-11e9-8462-92be3a6d6f64.png">

**Comment by jeveloper** [comment]
@kirankalyan5  Hey Kiran, setting textNumberOfLines={2} would not work when working in a typescript environment with checks. Unfortunately it needs to be an explicit parameter.

**Comment by josoma03** [comment]
@kirankalyan5 that's not working
