### ISSUE TITLE
Please make onTabPress work for selected tab as well

### ISSUE THREAD

**Issue by bgold0** [kirankalyan5/react-native-segmented-control-tab#45]
It would be very helpful if I could be alerted when a tab that is already selected has been selected also.  Ideal situation I am trying to solve is to un-select a selected tab.

At the moment, no action is recorded (at least in documentaiton)

**Comment by bgold0** [comment]
This would be REALLY helpful @kirankalyan5

**Comment by kirankalyan5** [comment]
@bgold0 if you enable `multiple` props, you can select the `selected tab` as well
