### ISSUE TITLE
Customise segment

### ISSUE THREAD

**Issue by aneena-thomas** [kirankalyan5/react-native-segmented-control-tab#46]
is it possible to customise segment like this?
![screen shot 2018-04-12 at 4 21 35 pm](https://user-images.githubusercontent.com/13118654/38673039-999c085e-3e6d-11e8-802a-a25cf1d1d67f.png)

**Comment by kirankalyan5** [comment]
you have full flexibility of styling the tabs so this should be doable.

**Comment by aneena-thomas** [comment]
how

**Comment by aneena-thomas** [comment]
i have done some styling but its looks like below
![simulator screen shot - iphone 6 - 2018-04-24 at 10 22 26](https://user-images.githubusercontent.com/13118654/39166823-6698292a-47a9-11e8-814d-bc7a287d8df2.png)

**Comment by kirankalyan5** [comment]
@aneena-thomas - I gave a quick try. Check this link https://snack.expo.io/@kirankalyan5/segmentedcontrolexample

**Comment by aneena-thomas** [comment]
wow thanks man its working
