### ISSUE TITLE
First tab has a broken view if values lower than 3

### ISSUE THREAD

**Issue by JayKurniawan** [kirankalyan5/react-native-segmented-control-tab#48]
I got this problem in iOS when I set the `values` to be only 2 (works fine on Android)

![img_0324 2](https://user-images.githubusercontent.com/6804018/39974305-1a14908a-5752-11e8-8d61-992735a1b1e2.jpg)

The tab works fine if I have more than  2 `values` 

Here's my code

```Javascript
             <SegmentedControlTab
                    values={['Aktif', 'Selesai']}
                    selectedIndex={this.state.selectedIndex}
                    onTabPress={this.handleIndexChange}
                    tabsContainerStyle={{ padding:20}}
                    tabStyle={{borderColor:'#a55eea'}}
                    tabTextStyle={{color:'#a55eea'}}
                    activeTabStyle={{backgroundColor:'#a55eea'}}
                />
```

**Comment by kirankalyan5** [comment]
Could you check if you have the latest version?

**Comment by Carlosp16** [comment]
I have the same error. I'm using the latest version. 3.2.2

**Comment by andrewlor** [comment]
I am having the same issue.

**Comment by kirankalyan5** [comment]
Hi guys, there was a similar render problem which was reported some time back.

Can you check this https://github.com/kirankalyan5/react-native-segmented-control-tab/issues/10?

it may help you.

**Comment by JayKurniawan** [comment]
@kirankalyan5 thanks
