### ISSUE TITLE
Tab Bar Image

### ISSUE THREAD

**Issue by sandeep0607** [kirankalyan5/react-native-segmented-control-tab#49]
Is there any possible way to add the image icon before the value/tab name ? if yes please help me. i do like this but the text is not adjusted with the image.
`badges={[
                        <Text style={styles.badgeText}>
                          <Image
                            style={styles.badgeImage1}
                            source={require("./Images/3.png")}
                          />Personal
                        </Text>,
                        <Text style={styles.badgeText}>
                          <Image
                            style={styles.badgeImage}
                            source={require("./Images/2.png")}
                          />Doctor
                        </Text>,
                        <Text style={styles.badgeText}>
                          <Image
                            style={styles.badgeImage2}
                            source={require("./Images/1.png")}
                          />Security
                        </Text>
                      ]}
                      values={["", "", ""]}`

**Comment by kirankalyan5** [comment]
Hi @sandeep0607 , you can do it this way.

create a function which renders inlineImage with text 

```
  renderValueWithImage(text, imageUri) {
    return (
      <Text> 
        <Image style={{marginRight: 5}} source={imageUri} />
        {text}
      </Text>
      )
  }
```
Pass it to the values props.
```
  <SegmentedControlTab
          values={[this.renderValueWithImage('Creation', creation),this.renderValueWithImage('Group', group)]}
          selectedIndex={this.state.selectedIndex}
          onTabPress={this.handleSingleIndexSelect}
        />
```

![img_e0b8b8892502-1](https://user-images.githubusercontent.com/13114538/42261852-c6f65984-7f69-11e8-934e-94a2d5ada1f8.jpeg)

**Comment by CapitanRedBeard** [comment]
Yeah the code above currently does not work

**Comment by ziyafenn** [comment]
Is there any update on this? I'd love to add an icon to my segmented tabs @kirankalyan5

**Comment by kirankalyan5** [comment]
@sandeep0607 @zhigang1992 the approach which I had shared is a hacky way to handle an image within a Text and pass it to values.

A nicer solution would be to enhance the component to handle images via props and make them configurable. 
Created issue #113 

I'm bit occupied at the moment, PR's most welcomed.

Thanks

**Comment by zhigang1992** [comment]
@kirankalyan5 wrong mention?

**Comment by kirankalyan5** [comment]
@zhigang1992 yes, sorry for that :D
