### ISSUE TITLE
Not working at all please check and update package

### ISSUE THREAD

**Issue by AppDev666** [kirankalyan5/react-native-segmented-control-tab#5]

**Comment by kirankalyan5** [comment]
@AppDev666 It's working all fine. Can you be more clear, where you are facing issue. 

Refer ReadME.

**Comment by AppDev666** [comment]
I follow Read ME.No segment bar is showing even change the styling and not clickable.
I switch to other option .If its working fine for you its OK.
Thanks for responding @kirankalyan5

**Comment by kirankalyan5** [comment]
Can you share your isuue (with screenshots and code ), so I can find a way to help you.
