### ISSUE TITLE
Customize tab press

### ISSUE THREAD

**Issue by clfristoe** [kirankalyan5/react-native-segmented-control-tab#52]
I would like to have an individual tab segment highlighted temporarily (using TouchableHighlight if possible) when tapped to give the user feedback that they've tapped. Is this possible with this library?

something like this:
https://facebook.github.io/react-native/docs/touchablehighlight.html#underlaycolor

**Comment by kirankalyan5** [comment]
@clfristoe in this library we use `TouchableOpacity` hence we could play around with `activeOpacity` to get similar behavior. Currently activeOpacity={1}. 
I can make it come from props.

**Comment by kirankalyan5** [comment]
Added activeTabOpacity to customize the tab press. Plese, check the latest version.

**Comment by clfristoe** [comment]
Thank you! @kirankalyan5
