### ISSUE TITLE
Weird padding on first tab

### ISSUE THREAD

**Issue by ziyafenn** [kirankalyan5/react-native-segmented-control-tab#54]
Hey there. 
I'm getting weird padding on the right side of first tab on the devices like iPhone X or iPads
![screenshot 2018-07-19 11 56 08](https://user-images.githubusercontent.com/314302/42936423-4fa3eeac-8b4c-11e8-8940-c253e8d9d1ff.png)

![screenshot 2018-07-19 11 59 08](https://user-images.githubusercontent.com/314302/42936505-88919b74-8b4c-11e8-9f2a-fc939abf9d89.png)
![screenshot 2018-07-19 11 59 03](https://user-images.githubusercontent.com/314302/42936509-8b512f14-8b4c-11e8-9457-29965167797a.png)

Any ideas?

**Comment by kirankalyan5** [comment]
Can you share the [snack](https://snack.expo.io/) for the same?

**Comment by kirankalyan5** [comment]
Please feel free to reopen if this still exists.

Also, request you to please share the code via  [snack](https://snack.expo.io/) so I could try helping you.
