### ISSUE TITLE
Support for accessibility

### ISSUE THREAD

**Issue by gbhasha** [kirankalyan5/react-native-segmented-control-tab#56]
Add accessibilityLabel for each tab, so that disabled user can easily identify the tab using voiceover or other assistive technology. And this also helps us to write proper functional test(automation test) using frameworks like Appium. Most of the testing frameworks expect an `accessibiltyLabel` or `testID` props to identify the item and trigger the event.

**Comment by saikrishna321** [comment]
Thanks @gbhasha much needed.

**Comment by Grohden** [comment]
So no `testID` then?
