### ISSUE TITLE
No UnitTest for the source code

### ISSUE THREAD

**Issue by gbhasha** [kirankalyan5/react-native-segmented-control-tab#58]
There is no unit test for the source code SegmentedControlTab.js

**Comment by kirankalyan5** [comment]
Totally agree! this is something the library is missing. On looking at the decent amount of PRs. I do prefer it is **must have**. Also, this is a reason it takes quite a while to merge a PR as it should be completely tested.

I have a must have TODO's for this library.

1. Introduce the unit test. (Jest)
2. introduce Flow and remove prototypes.
3. set up a prehook quality check on running eslint, flow, and test.

I'm but occupied now. If you would like to pick Unit test, it will be most appreciated.
