### ISSUE TITLE
What is the use case for having multiple option?

### ISSUE THREAD

**Issue by gbhasha** [kirankalyan5/react-native-segmented-control-tab#59]
Tabs solves the problem of separating content into sections and accessed via a single content area using a flat navigation structure that does not refresh the page when selected.

What is the rationale of having multiple option ?

**Comment by kirankalyan5** [comment]
This will enable the consumer to use the same component when they are interested in the values selected and not the content.

 FYI: Multiple here is an optional filed which by default is false.hence your expected way of tabs functioning works smoothly and it doesn't break the behavior.
