### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by gbhasha** [kirankalyan5/react-native-segmented-control-tab#60]
Given Example file is not working as expected. Seems there could be some problem accessing the package using `file:.../` protocol in `package.json`

Below is the error message.

> error: bundling failed: TypeError: Cannot read property 'bindings' of null

**Comment by kirankalyan5** [comment]
The reason should be because of the RN version. This should be fixed as part of #40.
Closing this as till will be tracked as part of #40.
