### ISSUE TITLE
activeTabTextStyle is crashing the app on android because the text is converted to RawText

### ISSUE THREAD

**Issue by rinaz-a** [kirankalyan5/react-native-segmented-control-tab#62]
I used to use this code that worked perfectly on iOs but is causing the app to crash on Android devices  : 
```
                            <SegmentedControlTab
                                values={['Non', '1 pers', '2 pers', '3 pers']}
                                selectedIndex={this.state.selectedIndex}
                                onTabPress={this.handleIndexChange}
                                borderRadius={20}
                                tabsContainerStyle={{ height: 40, backgroundColor: uiTheme.palette.blue, borderRadius: 30, marginBottom: 15, }}
                                tabStyle={{ backgroundColor: uiTheme.palette.white, borderWidth: 0, borderColor: 'transparent' }}
                                activeTabStyle={{ backgroundColor: uiTheme.palette.blue, marginTop: 2 }}
                                tabTextStyle={{ color: uiTheme.palette.blue, fontFamily: 'Dosis-Regular' }}
                                activeTabTextStyle={{ color: uiTheme.palette.white }} />
                            />
```

The error is the following : 
![image](https://user-images.githubusercontent.com/15831677/43210574-c3e7bebe-902f-11e8-9566-c4cb1a615e0c.png)

I solved it by simply removing the `activeTabTextStyle` property as the text is white by default in the activeTab. 👍 

But the `activeTabTextStyle` is still not functionnal

**Comment by kirankalyan5** [comment]
`activeTabTextStyle` is a styleObject and I believe this should not be causing the crash. If you could share the issue on a [snack](https://snack.expo.io/) https://snack.expo.io/ . 

I can give a try fixing it.

**Comment by rinaz-a** [comment]
I did this : https://snack.expo.io/S1liZWvE7

But it's pretty strange as here it work whereas I have the error as show over here on my computer.

Same results if I run the project on my phone from the snack or on my computer... At the moment I don't have enough time to dig more but I think it may be due to another module i'm using but it's pretty strange as if I comment this property everything is going well on my computer...

Thank you for your help and your time anyway

**Comment by kirankalyan5** [comment]
Sounds a bit strange for me aswell :(

**Comment by kirankalyan5** [comment]
Hi guys, I have published the latest version, could you update and check if this still exist?

https://www.npmjs.com/package/react-native-segmented-control-tab
