### ISSUE TITLE
The Multiple Option doesnt work !

### ISSUE THREAD

**Issue by nameisveeru** [kirankalyan5/react-native-segmented-control-tab#63]
Correct me if i am wrong .The 'multiple' prop set to true should allow us to select multiple tabs. It does not work that way with the tabclick. It works when the selectedIndices are hardcoded on the component itself. If there is other way of doing that. please let me know .
Thanks,
VeerU

**Comment by kirankalyan5** [comment]
```javascript
 <SegmentedControlTab
          multiple={true}
          selectedIndices={this.state.selectedIndices}
          onTabPress={this.handleMultipleIndexSelect}
        />
```

instead of `selectedIndex` you will be using `selectedIndices` prop.
