### ISSUE TITLE
New version of lib.

### ISSUE THREAD

**Issue by TimurAsayonok** [kirankalyan5/react-native-segmented-control-tab#64]
Hello @kirankalyan5, Could you update version of lib from `3.2.2`, because in this lib we added a lot of changes.

**Comment by kirankalyan5** [comment]
@TimurAsayonok I will be updating the version soon, It's been delayed as I'm in progress of adding few minor features which will result in a closing couple of issues :)

Could you specifically tell me what feature are you looking on the updated release?

**Comment by TimurAsayonok** [comment]
@kirankalyan5 Will be very helpful to see in new version commits:
- https://github.com/kirankalyan5/react-native-segmented-control-tab/commit/277afd18f04ff75d12729ce57684983d6f9fa7ff
- https://github.com/kirankalyan5/react-native-segmented-control-tab/commit/a04f590fa2d625b95aa6b93143c27b62a38d75cf
- https://github.com/kirankalyan5/react-native-segmented-control-tab/commit/5b20f1dc8f155b190e3e6b483bb257f5ff780c01

Best regards :)

**Comment by kirankalyan5** [comment]
@TimurAsayonok Thanks for letting me know, I will be publishing the new version very soon and keep you posted here!

**Comment by kirankalyan5** [comment]
New version v3.3.1 is published.

https://www.npmjs.com/package/react-native-segmented-control-tab
