### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by muhaimincs** [kirankalyan5/react-native-segmented-control-tab#68]
![photo6311910365591611398](https://user-images.githubusercontent.com/30996641/44134767-df2140e6-a098-11e8-93b6-32f3b4da095b.jpg)

does anyone ever experience this

**Comment by kirankalyan5** [comment]
Hi @muhaimincs it was reported earlier, you can go through this thread here. #10 

Also, It seems to be reported in [Rn](https://github.com/facebook/react-native/issues/17998).

I feel you can tackle this problem by playing around with the border 🤔

**Comment by kirankalyan5** [comment]
Closing this issue for now! Please feel free to re-open.
Thanks.
