### ISSUE TITLE
Border vs divider

### ISSUE THREAD

**Issue by waltermvp** [kirankalyan5/react-native-segmented-control-tab#69]
Im attempting to achieve the following design:
![screen shot 2018-08-15 at 6 48 52 pm](https://user-images.githubusercontent.com/1158238/44177438-f3897300-a0bb-11e8-8e53-ac41f4508fa2.png)

however when i set the borderColor i get the following expected result:
![screen shot 2018-08-15 at 6 51 33 pm](https://user-images.githubusercontent.com/1158238/44177509-45ca9400-a0bc-11e8-8267-c528c097187a.png)

Does it make sense to submit a PR for something named liked `dividerColor`?

**Comment by kirankalyan5** [comment]
I think you could achieve this design by playing around with borderRadius and border color.
![image](https://user-images.githubusercontent.com/13114538/44225346-952cc500-a18d-11e8-89d3-d58a70742777.png)

**Comment by waltermvp** [comment]
@kirankalyan5 thanks for your prompt response

I must be missing something. When i set borderColor is applies to both the border and the divider. I wanted a borderless design with the divider visible. Not sure how to achieve that.

**Comment by waltermvp** [comment]
@kirankalyan5 i understand the concern perhaps it should mimic UISegmentedControl behavior (i know apple does intentionally limit customization on controls when they feel the need to for design reasons) However im  not sure what that behavior is.

**Comment by kirankalyan5** [comment]
I would say, you could try convincing the designer for very minor changes like this and use the standard way.

**Comment by kirankalyan5** [comment]
@waltermvp closing this issue.
