### ISSUE TITLE
Add visual indicator for onPressIn to more closely match SegmentedControlIOS

### ISSUE THREAD

**Issue by tylerbuchea** [kirankalyan5/react-native-segmented-control-tab#71]
In the native iOS version of this component there is a visual indicator for when you press down but haven't yet let your finger up. It's a slightly lighter color than the fully active color.

I would like to open a PR to add this functionality to your component if you're cool with that I can start working on it.

![simulator screen shot - iphone 5s - 2018-09-14 at 12 31 12](https://user-images.githubusercontent.com/1241700/45571287-9d266600-b81a-11e8-841f-9422d52cc8b5.png)

**Comment by kirankalyan5** [comment]
Hi @tylerbuchea Sounds cool! please open a PR for the same 💪!

**Comment by kirankalyan5** [comment]
you can now use `activeTabOpacity`.
