### ISSUE TITLE
capturing presses on selected tab

### ISSUE THREAD

**Issue by chrismatchett** [kirankalyan5/react-native-segmented-control-tab#76]
Hi,

A question...wow would I go about capturing repeated presses on the currently selected tab as onTabPress fires when the selectedIndex changes?

Many thanks,

Chris

**Comment by kirankalyan5** [comment]
Hi, @chrismatchett sorry for the delay in response. We cannot capture repeated presses as the `onTabPress` only when the `(selectedIndex !== index`
FYR:
https://github.com/kirankalyan5/react-native-segmented-control-tab/blob/master/src/SegmentedControlTab.js#L63
