### ISSUE TITLE
Bleed over on ios

### ISSUE THREAD

**Issue by GavinThomas1192** [kirankalyan5/react-native-segmented-control-tab#83]
I'm posting this to add more attention to this previously filed bug. 
https://github.com/kirankalyan5/react-native-segmented-control-tab/issues/10

It's happening on ios, on device only. 
This SS from an iPhone 6s.
![image from ios](https://user-images.githubusercontent.com/28162527/50452610-f741c780-08ef-11e9-96d9-abd31c7057de.png)

I've tried. 
` const firstTabStyle = this.state.selectedIndex === 1 ? [{ borderRightWidth: 0 }] : {}
    const lastTabStyle = this.state.selectedIndex === 0 ? [{ borderLeftWidth: 0 }] : {}`

This didn't make a difference.
Thanks for the awesome package!

**Comment by champcmr** [comment]
I have also facing same issue. Hey @GavinThomas1192 have you find some solution to resolve it ?

**Comment by GavinThomas1192** [comment]
I had to do a 'hack' I believe this is an issue with RN vs this package. 
`tabStyle: {
    borderColor: colors.primaryAction,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },`

I had to add a 'rounding to the corners' remove the sharp edge. It's barely noticeable. But not straight.

**Comment by kirankalyan5** [comment]
closing this issue as it is inactive for a long time. you could try using the workaround.
Feel free to re-open the issue if this still exists.
