### ISSUE TITLE
Border radius style not overriding

### ISSUE THREAD

**Issue by spuntin** [kirankalyan5/react-native-segmented-control-tab#89]
Trying to set:

`activeTabStyle={{borderBottomLeftRadius: 0, borderBottomRightRadius: 0}`

but it doesn't appear to be overriding the default styles

**Comment by kirankalyan5** [comment]
Yes, it's expected, it would get overridden by the firstTabStyle,
 lastTabStyle. you could try playing around with borderRadius prop to achieve your expected behavior.
