### ISSUE TITLE
Styles not getting updated

### ISSUE THREAD

**Issue by bhavinpatolia** [kirankalyan5/react-native-segmented-control-tab#9]
I am using Segmented tab as per given example but its not updating style, its taking only default color of sky blue.
Code sample: 
<View style={styles.parent}>
        <View style={styles.flex1}>
          <SegmentedControl
            defaultPage={1}
            itemButtonViewStyle = {{
                width:200
            }}
            itemHeaderViewStyle = {{
                paddingVertical:10
            }}
            borderRadius={0}
            tabsContainerStyle={{height: 50, backgroundColor: '#F2F2F2'}}
            tabStyle={{backgroundColor: '#F2F2F2', borderWidth: 0}}
            activeTabStyle={{backgroundColor: 'white', marginTop: 2}}
            tabTextStyle={{color: '#444444', fontWeight: 'bold'}}
            activeTabTextStyle={{color: '#888888'}}
          >
            <SegmentedControl.Item
                title = {<Text>Nearby</Text>}
            >
                <View></View>
            </SegmentedControl.Item>
            <SegmentedControl.Item
                title = {<Text>Invites<Text>  </Text><Text style={styles.notificationItems}> 3 </Text></Text>}
            >
                <View></View>
            </SegmentedControl.Item>
        </SegmentedControl>
        </View>
        <View style={styles.flex11}>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  parent: {
    flex: 1,
    flexDirection: 'column',
  },
  flex1: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#211F47',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20    
  },
  flex11: {
    flex: 10,
    flexDirection: 'column'
  },
  notificationItems:{
    backgroundColor: '#CF2A52',
    color: 'white'
  }
});

**Comment by kirankalyan5** [comment]
Hi @bhavinpatolia, in above code I see you are using too many unsupported props (itemButtonViewStyle, itemHeaderViewStyle etc. ), which you shouldn't be..

you can re check the Documentation on custom styling and also refer this [example](https://github.com/kirankalyan5/react-native-segmented-control-tab/tree/master/Example/example).

**Comment by bhavinpatolia** [comment]
Updated one,
<SegmentedControl
            borderRadius={0}
                tabsContainerStyle={{height: 50, backgroundColor: '#211F47'}}
                tabStyle={{backgroundColor: '#211F47', borderWidth: 0}}
                activeTabStyle={{backgroundColor: 'white', marginTop: 2}}
                tabTextStyle={{color: '#211F47', fontWeight: 'bold'}}
                activeTabTextStyle={{color: '#211F47'}}
          >
Still not working

**Comment by kirankalyan5** [comment]
@bhavinpatolia I feel you are missing something, you can refer the example and cross check.

If it's still not working, then share the entire file, let me have a look.

**Comment by kirankalyan5** [comment]
@bhavinpatolia I have published the latest version, please verify now.
