### ISSUE TITLE
Make tabs fit to title length

### ISSUE THREAD

**Issue by hexatex** [kirankalyan5/react-native-segmented-control-tab#91]
I have one tab out of three that is longer than the rest and so it becomes abbreviated "Reports and Stu...".

Is it possible to make the tabs fit the width of the title instead of splitting the width between the tabs equally?

**Comment by fukemy** [comment]
any solution? too large width problem

**Comment by fukemy** [comment]
?

**Comment by kirankalyan5** [comment]
@fukemy you could try something like [this](https://github.com/kirankalyan5/react-native-segmented-control-tab/issues/161)

Also, you could play around with `tabsContainerStyle` & `tabStyle` to get this behavior.
